# Etapa de construcción
FROM node:22.13.1-alpine AS build
WORKDIR /app
ARG NPM_TOKEN

# ✅ Crear el archivo .npmrc para acceso privado
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build-prod

# Etapa de runtime, recomendable: nginx
FROM node:22.13.1-alpine
WORKDIR /app
COPY --from=build /app/dist/tfm-angular/browser /app
RUN npm install -g serve
EXPOSE 10000
CMD ["serve", "-s", "-l", "10000", "/app"]

#
#> docker build -t tfm-angular-prod .
#> docker run -it -p 8080:10000 --name tfm-angular-prod-app tfm-angular-prod
